### ISSUE TITLE
403 issue

### ISSUE THREAD

**Issue by anthonyst91** [FarshadTahmasbi/EzPermission#2]
Hello,
Today I've cloned again one of my Android projects using your library and unfortunately I got a 403 issue when fetching the artifact from your bintray server:

Could not GET 'https://androidisland.bintray.com/EzPermission/com/androidisland/ezpermission/ezpermission/0.1.4/ezpermission-0.1.4.pom'. Received status code 403 from server: Forbidden

Can you please take a look at this issue?

Thanks in advance!

**Comment by FarshadTahmasbi** [comment]
Hi Anthony
I'm on it, I'll let you know when is done
Regards

**Comment by FarshadTahmasbi** [comment]
@anthonyst91 Sorry for the trouble, It's fixed and available on the jcenter, Thanks for the participation

**Comment by anthonyst91** [comment]
@FarshadTahmasbi awesome, thank you for your very quick feedback ;) I really appreciate!

Keep up the good work,

Anthony
