### ISSUE TITLE
JCenter is deprecated

### ISSUE THREAD

**Issue by dimka-abramov** [FarshadTahmasbi/EzPermission#4]
Please republish the library to some other repository as jcenter is depracated and latest gradle versions return warnings.

More information can be found here: https://blog.gradle.org/jcenter-shutdown

**Comment by FarshadTahmasbi** [comment]
Thanks for the comment, It is now available on the jitpack, please check README.

**Comment by dimka-abramov** [comment]
Thank you the new instructions are working.
